ALTER TABLE employees ALTER COLUMN chuc_danh DROP NOT NULL;
ALTER TABLE employees ALTER COLUMN bo_phan DROP NOT NULL;
ALTER TABLE employees ALTER COLUMN ngay_gia_nhap DROP NOT NULL;
ALTER TABLE employees ALTER COLUMN email DROP NOT NULL;

